export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'repo',
        'release',
        'deps',
        'cli',
        'core',
        'format-validator',
        'http-linter',
        'http-testing',
        'openapi',
        'reporter',
        'request-dispatcher',
        'rfc-9110-rules',
        'sampler',
        'test-utils',
        'websocket-proxy',
        'core-testing',
        'astro-docs',
        'evaluation',
      ],
    ],
    'scope-empty': [2, 'never'],
  },
};
