export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'repo',
        'release',
        'deps',
        'cli',
        'common-cli',
        'core',
        'core-testing',
        'plugin-http-analyzer',
        'plugin-http-linter',
        'plugin-http-tester',
        'plugin-openapi',
        'plugin-reporter',
        'plugin-request-dispatcher',
        'plugin-sampler',
        'plugin-websocket-proxy',
        'rules-api-description-validation',
        'rules-rfc-9110',
        'thymian',
        'e2e',
      ],
    ],
    'scope-empty': [2, 'never'],
  },
};
