import {
  getHeader,
  or,
  requestHeader,
  responseHeader,
  type RuleViolationLocation,
} from '@thymian/core';
import { httpRule } from '@thymian/core';

import { parseChallenges } from '../utils/auth-parser.js';
import {
  requestAuthenticationHeaders,
  responseAuthenticationHeaders,
} from '../utils/authentication-header-names.js';

export default httpRule(
  'rfc9110/authentication-parameter-name-must-occur-once-per-challenge',
)
  .severity('error')
  // Implementable (outcome 1): this is a syntactic conformance check on the
  // auth-param syntax carried in authentication header field values, readable
  // via `validateHttpTransactions` + `getHeader` (header VALUES, not just
  // names). It applies to challenges (WWW-Authenticate / Proxy-Authenticate,
  // server-sent) and to credentials (Authorization / Proxy-Authorization,
  // client-sent). The `test` slot validates the server-generated challenges in
  // live responses (a server-behavior check); the request-side credentials are
  // validated against recorded traffic (`analyze`). In `test` the request is
  // generated by Thymian and is always well-formed, so the request-side scan
  // cannot produce a false positive there.
  .type('test', 'analytics')
  .url(
    'https://www.rfc-editor.org/rfc/rfc9110.html#name-authentication-parameters',
  )
  .description(
    'Authentication parameter names are matched case-insensitively and each parameter name MUST only occur once per challenge.',
  )
  .summary(
    'Each authentication parameter name MUST only occur once per challenge (matched case-insensitively).',
  )
  // Fire on HAR for both directions: response challenges (origin server /
  // proxy) and request credentials (client / user-agent).
  .appliesTo('origin server', 'proxy', 'client', 'user-agent')
  .rule((ctx) =>
    ctx.validateHttpTransactions(
      or(
        ...requestAuthenticationHeaders.map((h) => requestHeader(h)),
        ...responseAuthenticationHeaders.map((h) => responseHeader(h)),
      ),
      (req, res, location: RuleViolationLocation) => {
        const headers = [
          ...requestAuthenticationHeaders.flatMap(
            (header) => getHeader(req.headers, header) ?? [],
          ),
          ...responseAuthenticationHeaders.flatMap(
            (header) => getHeader(res.headers, header) ?? [],
          ),
        ];

        for (const headerValue of headers) {
          const challenges = parseChallenges(headerValue);
          for (const challenge of challenges) {
            const seenParams = new Set<string>();
            for (const param of challenge.parameters) {
              // Parameter names are matched case-insensitively (RFC 9110
              // Section 11.2), so normalize before checking for duplicates.
              const lowerName = param.name.toLowerCase();
              if (seenParams.has(lowerName)) {
                return [
                  {
                    location,
                    violation: {
                      message: `The authentication parameter "${param.name}" occurs more than once in a single challenge of "${headerValue}". Each authentication parameter name MUST only occur once per challenge.`,
                    },
                    findings: [],
                  },
                ];
              }
              seenParams.add(lowerName);
            }
          }
        }
        return [];
      },
    ),
  )
  .done();
