import { and, hasRequestBody, not, requestHeader } from '@thymian/core';
import { httpRule } from '@thymian/core';

export default httpRule(
  'rfc9110/client-must-not-generate-100-continue-without-content',
)
  .severity('error')
  // Request-side rule (constrains what the *client* generates). `test` is
  // dropped per #327: during a test the request is generated by Thymian, so the
  // user cannot drive the non-conformant case. `static` validates the request
  // shape described in the spec and `analytics` validates real recorded client
  // requests; both only need header-name and body presence (available via the
  // common projection), so a single shared filter-only rule covers them.
  .type('static', 'analytics')
  .url('https://www.rfc-editor.org/rfc/rfc9110.html#name-expect')
  .description(
    'A client MUST NOT generate a 100-continue expectation in a request that does not include content.',
  )
  // Request-side: match HAR requests (default request role `user-agent`) as
  // well as generically labelled clients.
  .appliesTo('client', 'user-agent')
  .rule((ctx) =>
    ctx.validateCommonHttpTransactions(
      and(requestHeader('expect', '100-continue'), not(hasRequestBody())),
    ),
  )
  .done();
