import { getHeader, statusCode } from '@thymian/core';
import { httpRule } from '@thymian/core';

export default httpRule(
  'rfc9110/proxy-must-send-proxy-authenticate-header-for-407-response',
)
  .severity('error')
  .type('analytics')
  .url(
    'https://www.rfc-editor.org/rfc/rfc9110.html#name-407-proxy-authentication-re',
  )
  .description(
    'The proxy MUST send a Proxy-Authenticate header field containing a challenge applicable to that proxy for the request.',
  )
  .appliesTo('proxy')
  // A 407 is only the responsibility of a proxy, so we scope to captured
  // transactions whose response was generated by a proxy participant
  // (meta.role === 'proxy'). Reading the real value lets us flag both an
  // absent and an empty Proxy-Authenticate challenge.
  .rule((ctx) =>
    ctx.validateCapturedHttpTransactions(
      statusCode(407),
      (transaction, location) => {
        if (transaction.response.meta.role !== 'proxy') {
          return [];
        }
        const value = getHeader(
          transaction.response.data.headers,
          'proxy-authenticate',
        );
        const list = Array.isArray(value)
          ? value
          : value != null
            ? [value]
            : [];
        const hasChallenge = list.some((v) => v.trim().length > 0);
        return hasChallenge
          ? []
          : [
              {
                location,
                violation: {
                  message:
                    'A proxy generated a 407 (Proxy Authentication Required) response without a valid Proxy-Authenticate header field. The proxy MUST send a Proxy-Authenticate header field containing a challenge applicable to that proxy for the request.',
                },
                findings: [],
              },
            ];
      },
    ),
  )
  .done();
