import {
  getHeader,
  requestHeader,
  type RuleViolationLocation,
} from '@thymian/core';
import { httpRule } from '@thymian/core';

export default httpRule('rfc9110/sender-should-send-q-parameter-last')
  .severity('warn')
  // Request-side rule: it constrains how the *sender* orders parameters in the
  // Accept request header. During `test` the request is generated by Thymian,
  // so the sender's ordering is not under user control and the rule cannot
  // meaningfully apply; during `lint` there is no real sender to observe. It is
  // therefore only validated against recorded traffic (`analyze`), where the
  // request originates from a real client.
  .type('analytics')
  .url('https://www.rfc-editor.org/rfc/rfc9110.html#name-accept')
  .summary(
    'Senders using weights SHOULD send "q" last (after all media-range parameters).',
  )
  .appliesTo('client', 'user-agent')
  .rule((ctx) =>
    ctx.validateHttpTransactions(
      requestHeader('accept'),
      (req, _res, location: RuleViolationLocation) => {
        const accept = getHeader(req.headers, 'accept');

        if (!accept) {
          return [];
        }

        const acceptHeaders = Array.isArray(accept) ? accept : [accept];

        const acceptValues = acceptHeaders.flatMap((header) =>
          header.split(','),
        );

        const malformedValues = acceptValues.filter((value) => {
          const params = value.split(';').map((param) => param.trim());
          const qParamIndex = params.findIndex((param) =>
            param.toLowerCase().startsWith('q='),
          );

          // The rule only applies to senders that actually use a weight. A
          // value without a "q" parameter is not malformed.
          return qParamIndex !== -1 && qParamIndex !== params.length - 1;
        });

        if (malformedValues.length > 0) {
          return [
            {
              location,
              violation: {
                message: `The weight parameter "q" SHOULD be sent as the last parameter. Malformed value(s) sent: ${malformedValues
                  .map((value) => value.trim())
                  .join(', ')}`,
              },
              findings: [],
            },
          ];
        }

        return [];
      },
    ),
  )
  .done();
