// RFC 9110's denominator (ADR-0021 §5, #156). RFC 9110 §17 itself enumerates
// no normative statements of its own — zero BCP 14 keywords in 27,018
// characters — so this package's unit is a **substitute**: one numbered
// section, anywhere in the document, that carries at least one BCP 14
// requirement-level keyword addressed to an HTTP participant. A section is
// not a statement, hence the substitute label.
//
// Counted from the document, never from the corpus: derived by walking the
// published RFC 9110 HTML (https://www.rfc-editor.org/rfc/rfc9110.html,
// June 2022) section by section and recording which of its own 291 numbered
// sections contain at least one of MUST, MUST NOT, SHALL, SHALL NOT, SHOULD,
// SHOULD NOT, MAY, REQUIRED, RECOMMENDED, NOT RECOMMENDED, OPTIONAL directly
// in their own text (not counting a keyword that only appears in a nested
// subsection — that subsection is its own, separate unit). 138 of 291
// numbered sections qualify; n = 138.
//
// This intentionally does **not** derive from what the 402 rules already
// cite: several keyword-bearing sections have no rule pointing at them
// today (see the PR for the list), which is exactly what a denominator
// counted from the corpus itself could never reveal.
//
// `rules` ships empty here on purpose — populating it is #157-#162's job,
// seeded from `./coverage-anchor-map.ts`.

import { defineCoverage } from '@thymian/core';

export default defineCoverage({
  source: {
    revision: 'RFC 9110 (June 2022)',
    countingRule:
      'One unit per numbered section carrying at least one BCP 14 ' +
      'requirement-level keyword (MUST, MUST NOT, SHALL, SHALL NOT, ' +
      'SHOULD, SHOULD NOT, MAY, REQUIRED, RECOMMENDED, NOT RECOMMENDED, ' +
      'OPTIONAL) addressed to an HTTP participant.',
    hasKeywordBasis: true,
    substituteLabel: 'section',
  },
  units: {
    '2.2': 'Requirements Notation',
    '2.3': 'Length Requirements',
    '2.4': 'Error Handling',
    '3.3': 'Connections, Clients, and Servers',
    '3.8': 'Caches',
    '4.1': 'URI References',
    '4.2.1': 'http URI Scheme',
    '4.2.2': 'https URI Scheme',
    '4.2.3': 'http(s) Normalization and Comparison',
    '4.2.4': 'Deprecation of userinfo in http(s) URIs',
    '4.3.2': 'http Origins',
    '4.3.3': 'https Origins',
    '4.3.4': 'https Certificate Verification',
    '5.1': 'Field Names',
    '5.3': 'Field Order',
    '5.4': 'Field Limits',
    '5.5': 'Field Values',
    '5.6.1.1': 'Sender Requirements',
    '5.6.1.2': 'Recipient Requirements',
    '5.6.3': 'Whitespace',
    '5.6.4': 'Quoted Strings',
    '5.6.7': 'Date/Time Formats',
    '6': 'Message Abstraction',
    '6.2': 'Control Data',
    '6.5.1': 'Limitations on Use of Trailers',
    '6.5.2': 'Processing Trailer Fields',
    '6.6.1': 'Date',
    '6.6.2': 'Trailer',
    '7.1': 'Determining the Target Resource',
    '7.2': 'Host and :authority',
    '7.4': 'Rejecting Misdirected Requests',
    '7.5': 'Response Correlation',
    '7.6': 'Message Forwarding',
    '7.6.1': 'Connection',
    '7.6.2': 'Max-Forwards',
    '7.6.3': 'Via',
    '7.7': 'Message Transformations',
    '7.8': 'Upgrade',
    '8.3': 'Content-Type',
    '8.3.1': 'Media Type',
    '8.3.3': 'Multipart Types',
    '8.4': 'Content-Encoding',
    '8.4.1.1': 'Compress Coding',
    '8.4.1.3': 'Gzip Coding',
    '8.5': 'Content-Language',
    '8.6': 'Content-Length',
    '8.7': 'Content-Location',
    '8.8.1': 'Weak versus Strong',
    '8.8.2.1': 'Generation',
    '8.8.3': 'ETag',
    '8.8.3.1': 'Generation',
    '9.1': 'Overview',
    '9.2.1': 'Safe Methods',
    '9.2.2': 'Idempotent Methods',
    '9.3.1': 'GET',
    '9.3.2': 'HEAD',
    '9.3.3': 'POST',
    '9.3.4': 'PUT',
    '9.3.5': 'DELETE',
    '9.3.6': 'CONNECT',
    '9.3.7': 'OPTIONS',
    '9.3.8': 'TRACE',
    '10.1.1': 'Expect',
    '10.1.2': 'From',
    '10.1.3': 'Referer',
    '10.1.4': 'TE',
    '10.1.5': 'User-Agent',
    '10.2.1': 'Allow',
    '10.2.2': 'Location',
    '10.2.4': 'Server',
    '11.2': 'Authentication Parameters',
    '11.4': 'Credentials',
    '11.5': 'Establishing a Protection Space (Realm)',
    '11.6.1': 'WWW-Authenticate',
    '11.6.2': 'Authorization',
    '11.7.1': 'Proxy-Authenticate',
    '11.7.2': 'Proxy-Authorization',
    '12.1': 'Proactive Negotiation',
    '12.4.2': 'Quality Values',
    '12.5.1': 'Accept',
    '12.5.2': 'Accept-Charset',
    '12.5.3': 'Accept-Encoding',
    '12.5.4': 'Accept-Language',
    '12.5.5': 'Vary',
    '13.1.1': 'If-Match',
    '13.1.2': 'If-None-Match',
    '13.1.3': 'If-Modified-Since',
    '13.1.4': 'If-Unmodified-Since',
    '13.1.5': 'If-Range',
    '13.2.1': 'When to Evaluate',
    '13.2.2': 'Precedence of Preconditions',
    '14': 'Range Requests',
    '14.1.2': 'Byte Ranges',
    '14.2': 'Range',
    '14.3': 'Accept-Ranges',
    '14.4': 'Content-Range',
    '14.5': 'Partial PUT',
    '15': 'Status Codes',
    '15.2': 'Informational 1xx',
    '15.2.2': '101 Switching Protocols',
    '15.3.1': '200 OK',
    '15.3.6': '205 Reset Content',
    '15.3.7': '206 Partial Content',
    '15.3.7.1': 'Single Part',
    '15.3.7.2': 'Multiple Parts',
    '15.3.7.3': 'Combining Parts',
    '15.4': 'Redirection 3xx',
    '15.4.1': '300 Multiple Choices',
    '15.4.2': '301 Moved Permanently',
    '15.4.3': '302 Found',
    '15.4.5': '304 Not Modified',
    '15.4.8': '307 Temporary Redirect',
    '15.4.9': '308 Permanent Redirect',
    '15.5': 'Client Error 4xx',
    '15.5.2': '401 Unauthorized',
    '15.5.4': '403 Forbidden',
    '15.5.6': '405 Method Not Allowed',
    '15.5.7': '406 Not Acceptable',
    '15.5.8': '407 Proxy Authentication Required',
    '15.5.9': '408 Request Timeout',
    '15.5.10': '409 Conflict',
    '15.5.12': '411 Length Required',
    '15.5.14': '413 Content Too Large',
    '15.5.17': '416 Range Not Satisfiable',
    '15.5.20': '421 Misdirected Request',
    '15.5.22': '426 Upgrade Required',
    '15.6': 'Server Error 5xx',
    '15.6.4': '503 Service Unavailable',
    '15.6.6': '505 HTTP Version Not Supported',
    '16.1.1': 'Method Registry',
    '16.2.1': 'Status Code Registry',
    '16.3.1': 'Field Name Registry',
    '16.3.2.1': 'Considerations for New Field Names',
    '16.4.1': 'Authentication Scheme Registry',
    '16.4.2': 'Considerations for New Authentication Schemes',
    '16.5.1': 'Range Unit Registry',
    '16.6.1': 'Content Coding Registry',
    '16.7': 'Upgrade Token Registry',
  },
  rules: {},
});
