openapi: 3.1.1
info:
  title: Test Todo Project
  version: 0.0.1
paths:
  /projects:
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: false
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                  required:
                    - id
                    - name
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
                - name
        required: true
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                required:
                  - id
                  - name
        "400":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /projects/{id}:
    get:
      parameters:
        - schema:
            type: string
            examples: ['1']
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                required:
                  - id
                  - name
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "204":
          description: Default Response
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /projects/{id}/todos:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
        required: true
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  done:
                    type: boolean
                  projectId:
                    type:
                      - "null"
                      - string
                required:
                  - id
                  - title
                  - done
        "400":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: false
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    done:
                      type: boolean
                    projectId:
                      type:
                        - "null"
                        - string
                  required:
                    - id
                    - title
                    - done
  /todos:
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: false
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    done:
                      type: boolean
                    projectId:
                      type:
                        - "null"
                        - string
                  required:
                    - id
                    - title
                    - done
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                title:
                  type: string
              required:
                - title
        required: true
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  done:
                    type: boolean
                  projectId:
                    type:
                      - "null"
                      - string
                required:
                  - id
                  - title
                  - done
        "400":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /todos/{id}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  done:
                    type: boolean
                  projectId:
                    type:
                      - "null"
                      - string
                required:
                  - id
                  - title
                  - done
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                done:
                  type: boolean
                projectId:
                  type: string
              additionalProperties: false
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  done:
                    type: boolean
                  projectId:
                    type:
                      - "null"
                      - string
                required:
                  - id
                  - title
                  - done
        "400":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        "204":
          description: Default Response
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
servers:
  - url: http://localhost:3000
    description: Development server
tags: []
