name: CI
on:
  push:
    branches:
      - main
      - rework-arch
  pull_request: {}
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install
        run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - name: run linter
        run: npx nx affected -t lint
      - name: run formatter check
        run: npx nx affected -t format:check

  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install
        run: npm ci
      - name: Check licenses
        run: npm run check:licenses

  main:
    strategy:
      matrix:
        version: [20, 22, 24]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - name: install
        run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - name: Build
        run: npx nx affected:build
      - name: Test
        run: npx nx affected:test
