name: E2E
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install
        run: npm ci
      - name: Build packages
        run: npx nx build thymian
      - name: Prepare test folder
        run: mkdir -p /tmp/thymian-e2e-test
      - name: Run Thymian E2E tests
        env:
          TARGET_FOLDER: '/tmp/thymian-e2e-test'
        run: npx nx e2e e2e-tests --outputStyle=static
